DROP TABLE MSP_SYS.D_ROLE CASCADE CONSTRAINTS;

CREATE TABLE MSP_SYS.D_ROLE
(
  ROLE_ID        INTEGER                        NOT NULL,
  ROLE_NAME      VARCHAR2(20 BYTE)              NOT NULL,
  ROLE_REMARK    VARCHAR2(20 BYTE),
  IS_VALID       INTEGER,
  CREATE_DATE    DATE                           NOT NULL,
  CREATE_BY      VARCHAR2(20 BYTE)              NOT NULL,
  LASTEDIT_DATE  DATE,
  LASTEDIT_BY    VARCHAR2(20 BYTE)
)
TABLESPACE MSP_SYS_DAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MSP_SYS.D_ROLE IS '角色主表';

COMMENT ON COLUMN MSP_SYS.D_ROLE.ROLE_ID IS '角色ID';

COMMENT ON COLUMN MSP_SYS.D_ROLE.ROLE_NAME IS '角色名称';

COMMENT ON COLUMN MSP_SYS.D_ROLE.ROLE_REMARK IS '角色备注';

COMMENT ON COLUMN MSP_SYS.D_ROLE.IS_VALID IS '角色是否有效，1有效；0，无效；';

COMMENT ON COLUMN MSP_SYS.D_ROLE.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN MSP_SYS.D_ROLE.CREATE_BY IS '修改人';

COMMENT ON COLUMN MSP_SYS.D_ROLE.LASTEDIT_DATE IS '最后修改时间';

COMMENT ON COLUMN MSP_SYS.D_ROLE.LASTEDIT_BY IS '最后修改人';


CREATE UNIQUE INDEX MSP_SYS.D_ROLE_PK ON MSP_SYS.D_ROLE
(ROLE_ID)
LOGGING
TABLESPACE MSP_SYS_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER MSP_SYS.TR_D_ROLE
   BEFORE INSERT
   ON MSP_SYS.D_ROLE    FOR EACH ROW
BEGIN
   SELECT SEQ_D_ROLE.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
END TR_D_ROLE;
/
