DROP TABLE MSP_SYS.D_MENU_ACTION_LIST CASCADE CONSTRAINTS;

CREATE TABLE MSP_SYS.D_MENU_ACTION_LIST
(
  LIST_ID      INTEGER                          NOT NULL,
  MENU_ID      INTEGER                          NOT NULL,
  ACTION_TYPE  VARCHAR2(50 BYTE),
  CREATE_DATE  DATE                             NOT NULL,
  CREATE_BY    VARCHAR2(20 BYTE)                NOT NULL,
  ACTION_NAME  VARCHAR2(50 BYTE)                NOT NULL
)
TABLESPACE MSP_SYS_DAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MSP_SYS.D_MENU_ACTION_LIST IS '用户主表';

COMMENT ON COLUMN MSP_SYS.D_MENU_ACTION_LIST.LIST_ID IS 'List ID';

COMMENT ON COLUMN MSP_SYS.D_MENU_ACTION_LIST.MENU_ID IS '菜单ID';

COMMENT ON COLUMN MSP_SYS.D_MENU_ACTION_LIST.ACTION_TYPE IS '按钮类型';


CREATE OR REPLACE TRIGGER MSP_SYS.TR_D_Menu_Action_List
   BEFORE INSERT
   ON MSP_SYS.D_MENU_ACTION_LIST    FOR EACH ROW
BEGIN
   SELECT SEQ_D_Menu_Action_List.NEXTVAL INTO :NEW.List_ID FROM DUAL;
END TR_D_Menu_Action_List;
/
