DROP TABLE MSP_SYS.D_USER_EDITPWD_LOG CASCADE CONSTRAINTS;

CREATE TABLE MSP_SYS.D_USER_EDITPWD_LOG
(
  USER_ID      NUMBER                           NOT NULL,
  USER_PWD     VARCHAR2(20 BYTE),
  EDIT_NUM     NUMBER,
  CREATE_DATE  DATE                             NOT NULL,
  CREATE_BY    VARCHAR2(20 BYTE)                NOT NULL
)
TABLESPACE MSP_SYS_DAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MSP_SYS.D_USER_EDITPWD_LOG IS '用户修改密码log表';

COMMENT ON COLUMN MSP_SYS.D_USER_EDITPWD_LOG.USER_ID IS '用户ID';

COMMENT ON COLUMN MSP_SYS.D_USER_EDITPWD_LOG.USER_PWD IS '用户密码';

COMMENT ON COLUMN MSP_SYS.D_USER_EDITPWD_LOG.EDIT_NUM IS '修改次数';

COMMENT ON COLUMN MSP_SYS.D_USER_EDITPWD_LOG.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN MSP_SYS.D_USER_EDITPWD_LOG.CREATE_BY IS '修改人';
